#!/bin/bash
set -x

if [ $TRAVIS_BRANCH == 'workflow/react' ] ; then
    git init

    git remote add deploy "git@donaldgeddes.ca:~/workflow-react.git"
    git config user.name "Travis CI"
    git config user.email "hi@donaldgeddes.ca"

    git add .
    git commit -m "Deploy"
    git push --force deploy master
else
    printf "\n\n\nNot deploying, since this branch isn't master.\n\n\n"
fi
