#!/bin/bash
set -x

if [ $TRAVIS_BRANCH == 'workflow/complete' ] ; then
    # Add remote
    git remote add deploy "git@donaldgeddes.ca:~/workflow-complete"
    git config user.name "Travis CI"
    git config user.email "hi@donaldgeddes.ca"

    git add .
    git commit -m "Deploy"
    git push --force deploy workflow/complete
else
    printf "\n\n\nNot deploying, since this branch isn't a deploy branch.\n\n\n"
fi
