#!/bin/bash

set -x

# Import the SSH deployment key
openssl aes-256-cbc -K $encrypted_1f9b5c217eed_key -iv $encrypted_1f9b5c217eed_iv -in deploy-key.enc -out deploy-key -d
rm deploy-key.enc # Don't need it anymore
chmod 600 deploy-key
mv deploy-key ~/.ssh/id_rsa

# Testing
echo $TRAVIS_BRANCH
