#!/bin/bash

set -x

# Import the SSH deployment key
openssl aes-256-cbc -K $encrypted_1f9b5c217eed_key -iv $encrypted_1f9b5c217eed_iv -in deploy-key.enc -out deploy-key -d

# Don't need it anymore
rm deploy-key.enc

# Ensure perms are a go
chmod 600 deploy-key

# Make key default
mv deploy-key ~/.ssh/id_rsa
