#!/bin/bash

# Check if .env file exists
if [ -e .env ]; then
    source .env
else
    echo "Error: please ensure your .env file has been configured"
    exit 1
fi

# Create main network for services to run on
docker network create ${NETWORK}

# Fetch latest nginx conf template
curl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl > nginx.tmpl

# Spin up nginx + letsencrypt companion
docker-compose -f nginx-proxy.yml up -d

# Spin up app-related services
docker-compose up -f docker-compose.yml -f docker-compose.production.yml up -d

# Build react
docker-compose run react npm run build
